config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  

  as :user do
    get '/register', to: 'devise/registrations#new', as: 'register'
    get '/login', to: 'devise/sessions#new', as: 'login'
    get '/logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end
  
  #member means instance - rather than applying to all user friendships
  resources :user_friendships do
    member do
      put :accept, :block
      #put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: 'feed'
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base

	belongs_to :user
	belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

	after_destroy :delete_mutual_friendship!

	state_machine :state, initial: :pending do
		after_transition on: :accept, do: [ :send_acceptance_email, :accept_mutual_friendship! ]
		after_transition on: :block, do: [:block_mutual_friendship ]

		state :blocked
		state :requested

		event :accept do
			transition any => :accepted
		end

		event :block do
			transition any => :blocked
		end
	end

	validate :not_blocked

	def self.request(user1, user2)
		transaction do
			friendship1 = create(user: user1, friend: user2, state: "pending")
			friendship2 = create(user: user2, friend: user1, state: "requested")
			
			friendship1.send_request_email if !friendship1.new_record?
			friendship1
		end
	end


	def not_blocked
		if UserFriendship.exists?(user_id: user_id, friend_id: friend_id, state: 'blocked') ||
		   UserFriendship.exists?(user_id: friend_id, friend_id: user_id, state: 'blocked')
			errors.add(:base, "The friendship cannot be added.")
		end
	end


	def send_request_email
		UserNotifier.friend_requested(id).deliver
	end


	def send_acceptance_email
		UserNotifier.friend_request_accepted(id).deliver
	end


	def mutual_friendship
		# grab the mutual friendship and update without using
		# the state machine so not so many callbacks
		self.class.where({user_id: friend_id, friend_id: user_id}).first	
	end


	def accept_mutual_friendship!
		mutual_friendship.update_attribute(:state, 'accepted')
	end


	def delete_mutual_friendship!
		mutual_friendship.delete
	end


	def block_mutual_friendship
		mutual_friendship.update_attribute(:state, 'blocked') if mutual_friendship
	end

end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
	before_filter :authenticate_user!
	before_action :set_user_friendship, only: [:accept, :destroy]
	rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
	respond_to :html, :json

	def index
		@user_friendships = UserFriendshipDecorator.decorate_collection(friendship_association.all)
		respond_with @user_friendships
	end


	def new
		if params[:friend_id]
			@friend = User.where(profile_name: params[:friend_id]).first
			raise ActiveRecord::RecordNotFound if @friend.nil?
			@user_friendship = current_user.user_friendships.new(friend: @friend)
		else
			flash[:error] = "Friend required"
		end
	end


	def edit
		@friend = User.where(profile_name: params[:id]).first		
		@user_friendship = current_user.user_friendships.where(friend_id: @friend.id).first.decorate
	end


	def create
		if params[:user_friendship] && params[:user_friendship].has_key?(:friend_id)		
			@friend = User.where(profile_name: params[:user_friendship][:friend_id]).first
			@user_friendship = UserFriendship.request(current_user, @friend)
			respond_to do |format|
				if @user_friendship.new_record?
					format.html do
						flash[:error] = "There was a problem creating that friendship"
						redirect_to profile_path(@friend)
					end
					format.json { render json: @user_friendship.to_json, status: :precondition_failed }
				else
					format.html do
						flash[:success] = "Friend request sent."
						redirect_to profile_path(@friend)
					end	
					format.json { render json: @user_friendship.to_json }				
				end
			end
		else
			flash[:error] = "Friend required"
			redirect_to root_path
		end
	end


	def accept
		if @user_friendship.accept!
			flash[:success] = "You are now friends with #{@user_friendship.friend.first_name}"
		else
			flash[:success] = "That friendship could not be accepted"
		end
		redirect_to user_friendships_path
	end


	def block
		@user_friendship = current_user.user_friendships.find(params[:id])
		if @user_friendship.block!
			flash[:success] = "You have blocked #{@user_friendship.friend.first_name}"
		else
			flash[:error] = "That person could not be blocked"
		end
		redirect_to user_friendships_path
	end


	def destroy
		if @user_friendship.destroy			
			flash[:success] = "You are no longer friends"
		end
		redirect_to user_friendships_path
	end



	private

	def friendship_association
		case params[:list]
		when nil
			current_user.user_friendships
		when 'blocked'
			current_user.blocked_user_friendships
		when 'pending'	
			current_user.pending_user_friendships
		when 'accepted'
			current_user.accepted_user_friendships
		when 'requested'
			current_user.requested_user_friendships
		end 
	end

	def record_not_found
		render file: 'public/404', status: :not_found
	end

	def set_user_friendship
		@user_friendship = current_user.user_friendships.find(params[:id])
	end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_friendship_params
        params.require(:user_friendship).permit(:id, :user_id, :friend_id)
    end
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/views/user_friendships/edit.html.erb
<div class="page-header">
	<h1>Friendships</h1>
</div>

<h3><%= @user_friendship.sub_message %></h3>

<div class="form-action">

	<% if @user_friendship.requested? %>
		<%= form_for @user_friendship, url: accept_user_friendship_path(@user_friendship), method: :put do |form| %>

		<%= submit_tag "Accept Friendship", class: 'btn btn-primary' %>
		<% end %>
	<% end %>

		<%= form_for @user_friendship, url: block_user_friendship_path(@user_friendship), method: :put do |form| %>

		<%= submit_tag "Block this user", class: 'btn' %>
		<% end %>


	<%= form_for @user_friendship, url: user_friendship_path(@user_friendship), method: :delete do |form| %>

	<%= submit_tag "Delete Friendship", class: 'btn btn-danger' %>
	<% end %>

</div>

app/views/user_friendships/index.html.erb
<div class="page-header">
	<h1>Friends</h1>
</div>


<div>
	<strong>Friend List</strong>
	<%= link_to 'Blocked', user_friendships_path(list: 'blocked') %>
	<%= link_to 'Requested', user_friendships_path(list: 'requested') %>
	<%= link_to 'Accepted', user_friendships_path(list: 'accepted') %>
	<%= link_to 'Pending', user_friendships_path(list: 'pending') %>

</div>

<% @user_friendships.each do |friendship| %>

<div id="<%= dom_id(friendship) %>">
	<%= link_to friendship.friend.full_name, profile_path(friendship.friend.profile_name) %>

	<% if friendship.pending? %>
	<em>Friendship is pending.</em>
	<%= link_to "delete request", edit_user_friendship_path(friendship.friend.profile_name) %>

	<% end %>

	<% if friendship.requested? %>
	<p>Requested</p>
		<%=link_to "Accept Friendship", edit_user_friendship_path(friendship.friend.profile_name) %>
	<% end %>

	<% if friendship.accepted? %>
	<em>Current Friend.</em>
		<%= friendship.updated_at %><%= link_to "Update friendship", edit_user_friendship_path(friendship.friend.profile_name) %>
	<% end %>
</div>
<% end %>

app/views/user_friendships/new.html.erb
<% if @friend %>
	<h1><%= @friend.full_name %></h1>
	<p>Do you really want to friend <%= @friend.full_name %>?</p>
	<%= form_for @user_friendship, method: :post do |form| %>
		<%= form.hidden_field :friend_id, value: @friend.profile_name %>
		<%= submit_tag "Yes, Add Friend", class: "btn btn-primary" %>
		<%= link_to "Cancel", profile_path(@friend), class: 'btn' %>
	<% end %>
<% end %>