config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  

  as :user do
    get '/register', to: 'devise/registrations#new', as: 'register'
    get '/login', to: 'devise/sessions#new', as: 'login'
    get '/logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end
  
  #member means instance - rather than applying to all user friendships
  resources :user_friendships do
    member do
      put :accept, :block
      #put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: 'feed'
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit]  
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    if params[:status] && params[:status].has_key?(:user_id)
      params[:status].delete(:user_id)
    end
    
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end




  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = current_user.statuses.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
        params.require(:status).permit(:id, :user_id, :content)
    end

    def has_status_params?
      params[:status]
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= simple_form_for @status do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>





  <div class="form-group">
    <%= f.input :content, input_html: { placeholder: "What's on your mind?", class: "form-control" } %>
  </div>
  <div class="actions">
    <%= f.submit "Post Status", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="page-header">
    	<h2>Post Status</h2>
    	<%= link_to 'Back', statuses_path %>
    </div>

		<%= render 'form' %>

	</div>
</div>

app/views/statuses/index.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="page-header">
          <h2>Needs Feed
            <%= link_to "New Post", new_status_path, class: "btn btn-primary btn-sm white new-post-button" %>
          </h2>
    </div>


    <% @statuses.each do |status| %>
    <% if can_display_status? status %>

      <div class="row">
        <div class="col-xs-8">
          <h4><%= link_to status.user.full_name, profile_path(status.user) %></h4>
        </div>
        <div class="col-xs-4">
          <div class="btn-group">
            <button type="button" class="btn btn-default btn-link dropdown-toggle" data-toggle="dropdown">
              More<span class="caret"></span>
            </button>
            <ul class="dropdown-menu dropdown-menu-right" role="menu">
              <li><%= link_to "edit", edit_status_path(status) %></li>
              <li><%= link_to "delete", status, method: :delete, data: {confirm: "Are you sure you want to delete your status?" } %> </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-10 col-sm-8">
          <p><%= status.content %></p>
          <small><%= time_ago_in_words(status.created_at) + " ago" %></small>
        </div>
      </div>

      <hr>
      <% end %>
      <% end %>
  </div>
</div>

app/views/statuses/new.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="page-header">
    	<h2>Post Status</h2>
    	<%= link_to 'Back', statuses_path %>
    </div>

<%= render 'form' %>


	</div>
</div>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name: <%= @status.user.full_name %></strong>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>