config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  

  as :user do
    get '/register', to: 'devise/registrations#new', as: 'register'
    get '/login', to: 'devise/sessions#new', as: 'login'
    get '/logout', to: 'devise/sessions#destroy', as: 'logout'
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end
  
  #member means instance - rather than applying to all user friendships
  resources :user_friendships do
    member do
      put :accept, :block
      #put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: 'feed'
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">  
</head>
<body>

	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "Treebook", root_path, class: "navbar-brand" %>
	    </div>
	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><%= link_to "News Feed", feed_path %></li>
	      </ul>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<li><%= link_to "Friends", user_friendships_path %></li>
						<li><%= link_to current_user.first_name, edit_user_registration_path %></li>
	    			<li><%= link_to "Logout", logout_path %></li>
	    		<% elsif %>
						<li><%= link_to "Register", register_path %></li>
						<li><%= link_to "Log In", login_path %></li>	    		
	    		<% end %>
    		</ul>	      
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>


	<div class="container">
	<% flash.each do |type, message| %>
		<div class="alert <%= flash_class type %>" role="alert">
   			<%= message %>
   		</div>	
   	<% end %>


		<%= yield %>

	</div>

</body>
</html>